In [2]:
print ("hola")

hola


# Numpy
* Que son? Son matrices de N-dimensiones que coleccionas datos de un mismo tipo o diferente

In [3]:
import numpy as np # importar la libreria


In [97]:
m=np.array([[0,1,2],[3,4,5]]) # 2 filas y 3 columnas

In [98]:
print(m)

[[0 1 2]
 [3 4 5]]


3

In [7]:
print(m.shape) # muestra las dimensiones de la matriz

(2, 3)


In [46]:
x=['1','2']

x[0]="123"
print(x)
print(x[1])

['123', '2']
2


In [10]:
print(m[1]) # muestra la segunda 

[3 4 5]


In [12]:
y=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
print(y[:,2]) # solo extrae los elementos 2,5,8

print(y[:,2]) # extraer todas las filas y solo la columna 3
print(y[0:,2]) #  extraer todas las filas y solo la columna 3



print(y[0:1,2]) # solo extrae la fila 1 y columna 3

print(y[0:2,2]) # solo extrae fila 0 y 1 y columna 3.
 



[2 5 8]
[2 5 8]
[2 5 8]
[2]
[2 5]


In [20]:
print(y[0:2,:]) # todas las columnas solo fila 0 y 1.

[[0 1 2]
 [3 4 5]]


In [22]:
a=np.array([1,0.1,2])
print (a)

b=np.array([1,"1",0.1])
print(b)

[1.  0.1 2. ]
['1' '1' '0.1']


In [24]:
# Otros comandos utiles
x = np.zeros((2,2)) # matriz de puros ceros
print(x) 

[[0. 0.]
 [0. 0.]]


In [25]:
x=np.ones((2,2)) # matriz de puros unos
print(x)

[[1. 1.]
 [1. 1.]]


In [26]:
x=np.full((2,2),8) # matriz rellenada con el numero a criterio de elccion
print(x)

[[8 8]
 [8 8]]


In [41]:
x=np.random.random((2,3))
print(x)

[[0.13744551 0.3565013  0.42678318]
 [0.71480004 0.154101   0.36341149]]


In [49]:
# COPIAR 
m=np.array([[0,1,2],[3,4,5]])

x=m # esto es una referenciacion

print(x)


[[0 1 2]
 [3 4 5]]


In [51]:

m[0,1]=9
print(x)

[[0 9 2]
 [3 4 5]]


In [52]:
y=m.copy()
print(y)

[[0 9 2]
 [3 4 5]]


In [53]:
m[0,1]=1
print(y)

[[0 9 2]
 [3 4 5]]


In [54]:
# Tipos de datos
x=np.array([0,1,2])
print(x.dtype)


int32


In [55]:
m=x.astype(np.float32)
print(m.dtype)

float32


In [59]:
# Operaciones matematicas
# Suma
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(a)
print(b)

print(a+b) # suma comun 
print(np.add(a,b)) #suma utilizando numpy

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [63]:
# Resta
print(a-b)
print(np.subtract(a,b))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [65]:
# Division
print (a/b)
print(np.divide(a,b))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [67]:
# multiplicacion
print (a*b)

# raiz cuadrada
print(np.sqrt(a))

[[ 5 12]
 [21 32]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [71]:
# Reshaping 
x=np.arange(8) 
print(x)

y=np.reshape(x,(2,4))
print(y)

a=np.array([[1,2],[3,4],[5,6]])
print(a)

b=np.reshape(a,(2,3))
print(b)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [92]:
# Random seed 
x=np.random.seed(1)
x=np.random.randint(3,high=100,size=(2,2))
print(x)

[[40 15]
 [75 12]]


In [88]:
x=np.array([[1,-2,3],[4,5,6],[7,8,-9]])
print(x)
print(x.min())
print(x.max())

print(x.min(axis=0)) # cuando axis es 0 significa columna y cuando axis es 1 significa fila
print(x.max(axis=1))


[[ 1 -2  3]
 [ 4  5  6]
 [ 7  8 -9]]
-9
8
[ 1 -2 -9]
[3 6 8]


In [91]:
print(np.sum(x))
print(np.sum(x,axis=1))
print(np.mean(x))
print(np.var(x))
print(np.mean(x,axis=0))

23
[ 2 15  6]
2.5555555555555554
25.135802469135804
[4.         3.66666667 0.        ]
